-- Generals
reload("user.plugins")
reload("user.options")
reload("user.custom.functions")
reload("user.custom.autocommands")
reload("user.keymaps")

-- IDE Essentials
reload("user.cmp")
reload("user.lsp")
reload("user.treesitter")

-- Plugin config
reload("user.colorizer")
reload("user.cybu")
reload("user.fidget")
reload("user.flit")
reload("user.markdown")
reload("user.noice")
reload("user.notify")
reload("user.nvim-tree")
reload("user.harpoon")
reload("user.lastplace")
reload("user.spectre")
reload("user.telescope")
reload("user.todo")
reload("user.winsep")
reload("user.whichkey")
reload("user.zen")
reload("user.zoomwintab")
