-- Generals
reload("user.plugins")
reload("user.options")
reload("user.custom.functions")
reload("user.custom.autocommands")
reload("user.keymaps")

-- Theme
reload("user.theme")

-- IDE Essentials
reload("user.cmp")
reload("user.lsp")
reload("user.treesitter")

-- Plugin config
reload("user.bqf")
reload("user.bufferline")
reload("user.colorizer")
-- reload("user.comment")
reload("user.cybu")
reload("user.dashboard")
reload("user.dial")
reload("user.fidget")
reload("user.flit")
-- reload("user.fold")
reload("user.git")
reload("user.harpoon")
reload("user.hlslens")
reload("user.iswap")
reload("user.image")
reload("user.lastplace")
reload("user.markdown")
reload("user.mini")
reload("user.navbuddy")
reload("user.noice")
reload("user.notify")
reload("user.nvim-tree")
reload("user.oil")
reload("user.portal")
reload("user.screensaver")
reload("user.scrollbar")
reload("user.spectre")
reload("user.surround")
reload("user.terminal")
reload("user.telescope")
reload("user.trouble")
reload("user.todo")
reload("user.winsep")
reload("user.whichkey")
reload("user.zen")
reload("user.zoom")

-- Experimental
-- reload("user.styler")
-- https://github.com/rareitems/anki.nvim
