require("user.plugins")
require("user.options")
require("user.keymaps")
require("user.autocommands")
require("user.lsp")
require("user.treesitter")

require("user.cybu")
require("user.nvim-tree")
require("user.telescope")
require("user.spectre")
require("user.harpoon")
require("user.whichkey")
require("user.zen")
